[package]
name = "myip"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.25", features = ["full"] }
axum = { version = "0.6.4", features = ["http2"] }
axum-extra = { version = "0.4.2", features = ["erased-json"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.3.5", features = ["cors"] }
axum-client-ip = "0.3.1"
ipgeolocate = { git = "https://github.com/jerryshell/ipgeolocate", default-features = false, features = [
    "h1-client-rustls",
] }
anyhow = "1.0.68"
cached = "0.42.0"

[profile.release]
lto = true
strip = true
