[package]
name = "myip"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.22", features = ["full"] }
axum = { version = "0.6.1", features = ["http2"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.3.5", features = ["cors"] }
axum-client-ip = "0.3.0"

[profile.release]
lto = true
strip = true
